# Generated by Django 5.2.1 on 2025-06-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessalert',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='businessalert',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='businessalert',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='businessgoal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='businessgoal',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='businessmetrics',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='businessmetrics',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='quickaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quickaction',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='businessalert',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessalert',
            name='resolved_by_employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessalert',
            name='updated_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessgoal',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessgoal',
            name='updated_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessmetrics',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessmetrics',
            name='updated_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='updated_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickaction',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickaction',
            name='updated_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
