# Generated by Django 5.2.1 on 2025-06-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_remove_businessalert_created_by_and_more'),
    ]

    operations = [
    ]
