# Generated by Django 5.2.1 on 2025-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customerdocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customerdocument',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customerfeedback',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customerfeedback',
            name='responded_by',
        ),
        migrations.RemoveField(
            model_name='customerfeedback',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customernote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customernote',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='responded_by_id',
            field=models.IntegerField(blank=True, help_text='Employee ID who responded', null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='customernote',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='customernote',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
    ]
