# Generated by Django 5.2.1 on 2025-06-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='created_by',
        ),
        migrations.AddField(
            model_name='service',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
    ]
