# Generated by Django 5.2.1 on 2025-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='servicebay',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='servicebay',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='servicequeue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='servicequeue',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='service',
            name='deleted_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='servicebay',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='servicebay',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='deleted_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='servicequeue',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='servicequeue',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
    ]
