# Generated by Django 5.2.1 on 2025-06-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_deleted_by_remove_service_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Date when payment was completed', null=True),
        ),
    ]
