# Generated by Django 5.2.1 on 2025-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='subscriptiondiscount',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subscriptiondiscount',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='subscriptionusage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subscriptionusage',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondiscount',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondiscount',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionusage',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionusage',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
    ]
