# Generated by Django 5.2.1 on 2025-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cardtransaction',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='paymentrefund',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentrefund',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='paymentsplit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentsplit',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
    ]
