# Generated by Django 5.2.1 on 2025-06-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by_user_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
    ]
