# Generated by Django 5.2.1 on 2025-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptitem',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='suppliercategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='suppliercategory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='suppliercontact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='suppliercontact',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='supplierdocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplierdocument',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='supplierevaluation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplierevaluation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='deleted_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='suppliercategory',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='suppliercategory',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
    ]
