# Generated by Django 5.2.1 on 2025-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryalert',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventoryalert',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='inventorycategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventorycategory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='itemconsumption',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemconsumption',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='itemexpiry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemexpiry',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='itemlocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemlocation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='itemserial',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemserial',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stocktakecount',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stocktakecount',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='inventoryalert',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='inventoryalert',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='deleted_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='itemconsumption',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='itemconsumption',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='itemexpiry',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='itemexpiry',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='itemlocation',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='itemlocation',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='itemserial',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='itemserial',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='stocktakecount',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='stocktakecount',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
    ]
