# Generated by Django 5.2.1 on 2025-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='notificationcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationcategory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='notificationdigest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationdigest',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='notificationcategory',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='notificationcategory',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='notificationdigest',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='notificationdigest',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
    ]
