# Generated by Django 5.2.1 on 2025-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='analyticsevent',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='businessmetrics',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='businessmetrics',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='reportexport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportexport',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='reportschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportschedule',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='reportwidget',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportwidget',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='businessmetrics',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='businessmetrics',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='reportwidget',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='reportwidget',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
    ]
