# Generated by Django 5.2.1 on 2025-06-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='break_end_time',
            field=models.DateTimeField(blank=True, help_text='Time when break ended', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_start_time',
            field=models.DateTimeField(blank=True, help_text='Time when break started', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_break_duration',
            field=models.DurationField(blank=True, help_text='Total break duration', null=True),
        ),
    ]
