# Generated by Django 5.2.1 on 2025-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='position',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='position',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='training',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='training',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='trainingparticipant',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trainingparticipant',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='trainingparticipant',
            name='created_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
        migrations.AddField(
            model_name='trainingparticipant',
            name='updated_by_id',
            field=models.IntegerField(blank=True, help_text='User ID from public schema', null=True),
        ),
    ]
